# Form implementation generated from reading ui file 'windows_ui/ui_files/loading_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadingWindow(object):
    def setupUi(self, LoadingWindow):
        LoadingWindow.setObjectName("LoadingWindow")
        LoadingWindow.resize(486, 172)
        LoadingWindow.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadingWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_loading = QtWidgets.QFrame(LoadingWindow)
        self.frame_loading.setStyleSheet("* {\n"
"border: 0;\n"
"color: white;\n"
"}\n"
"\n"
"QFrame  {\n"
"    background-color: rgb(49, 49, 74);\n"
"   border-radius: 10px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"max-height: 5px;\n"
"border: 0;\n"
"color: transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color:rgb(98, 98, 148) ;\n"
"}")
        self.frame_loading.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_loading.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_loading.setObjectName("frame_loading")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_loading)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_info_loading = QtWidgets.QLabel(self.frame_loading)
        self.label_info_loading.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_info_loading.setFont(font)
        self.label_info_loading.setStyleSheet("min-height:: 100px;")
        self.label_info_loading.setObjectName("label_info_loading")
        self.verticalLayout_2.addWidget(self.label_info_loading)
        self.progress_bar_loading = QtWidgets.QProgressBar(self.frame_loading)
        self.progress_bar_loading.setProperty("value", 24)
        self.progress_bar_loading.setObjectName("progress_bar_loading")
        self.verticalLayout_2.addWidget(self.progress_bar_loading)
        self.label_loading = QtWidgets.QLabel(self.frame_loading)
        self.label_loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_loading.setObjectName("label_loading")
        self.verticalLayout_2.addWidget(self.label_loading)
        self.verticalLayout.addWidget(self.frame_loading)

        self.retranslateUi(LoadingWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadingWindow)

    def retranslateUi(self, LoadingWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadingWindow.setWindowTitle(_translate("LoadingWindow", "Dialog"))
        self.label_info_loading.setText(_translate("LoadingWindow", "Getting the infos..."))
        self.label_loading.setText(_translate("LoadingWindow", "Loading....."))
